<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Chaplin Api'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css') ?>
       <script src="<?php echo $this->basePath() ?>/js/lib/require.js" data-main="<?php echo $this->basePath() ?>/js/app/apps"></script>
    </head>
    <body>
        
    </body>
</html>
